
ASSESSMENT_PENDING = "PENDING"
ASSESSMENT_APPROVED = "APPROVED"
ASSESSMENT_REJECTED = "REJECTED"
ASSESSMENT_TOKEN_GENERATED = "TOKEN_GENERATED"
ASSESSMENT_TOKEN_VERIFIED = "TOKEN_VERIFIED"
ASSESSMENT_RECON_RUNNING = "RECON_RUNNING"
ASSESSMENT_SCAN_RUNNING = "SCAN_RUNNING"
ASSESSMENT_COMPLETED = "COMPLETED"
ASSESSMENT_FAILED = "FAILED"

VERIFICATION_PENDING = "PENDING"
VERIFICATION_TOKEN_GENERATED = "TOKEN_GENERATED"
VERIFICATION_VERIFIED = "VERIFIED"
VERIFICATION_FAILED = "FAILED"
VERIFICATION_DNS_PREFIX = "_aegis-verification"

# Audit Event Types

EVENT_ASSET_REGISTERED = "ASSET_REGISTERED"
EVENT_ASSET_VERIFIED = "ASSET_VERIFIED"

EVENT_ASSESSMENT_REQUESTED = "ASSESSMENT_REQUESTED"
EVENT_ASSESSMENT_APPROVED = "ASSESSMENT_APPROVED"

EVENT_TOKEN_GENERATED = "TOKEN_GENERATED"
EVENT_TOKEN_VERIFIED = "TOKEN_VERIFIED"

EVENT_RECON_STARTED = "RECON_STARTED"
EVENT_RECON_COMPLETED = "RECON_COMPLETED"

EVENT_SCAN_STARTED = "SCAN_STARTED"
EVENT_SCAN_COMPLETED = "SCAN_COMPLETED"

EVENT_CORRELATION_STARTED = "CORRELATION_STARTED"
EVENT_CORRELATION_COMPLETED = "CORRELATION_COMPLETED"

